title: Chris's Titles
author: Chris LoPresti
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Check out this new description!!!
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
